export const SET_USER_ARTEFACTS = "SET_USER_ARTEFACTS";
export const ADD_NEW_ARTEFACT = "ADD_NEW_ARTEFACT";
export const SET_SELECTED_ARTEFACT = "SET_SELECTED_ARTEFACT";
export const UPDATE_SELECTED_ARTEFACT = "UPDATE_SELECTED_ARTEFACT";
export const DELETE_SELECTED_ARTEFACT = "DELETE_SELECTED_ARTEFACT";
export const SET_ARTEFACT_COMMENTS = "SET_ARTEFACT_COMMENTS";