export const SET_USER_ARTEFACTS = "SET_USER_ARTEFACTS";
export const SET_ARTEFACT_IN_CACHE = "ADD_ARTEFACT_TO_CACHE";
export const ARTEFACT_DATA = "ARTEFACT_DATA";
export const ARTEFACT_COMMENTS = "ARTEFACT_COMMENTS";
