export const SET_USER_ARTEFACTS = "SET_USER_ARTEFACTS";
export const SET_SELECTED_ARTEFACT = "SET_SELECTED_ARTEFACT";
export const SET_ARTEFACT_COMMENTS = "SET_ARTEFACT_COMMENTS";
export const ADD_ARTEFACT_COMMENT = "ADD_ARTEFACT_COMMENT";
