export const SET_USER_GROUPS = "SET_USER_GROUPS";
export const SET_SELECTED_GROUP = "SET_SELECTED_GROUP";
export const SET_SELECTED_GROUP_ARTEFACTS = "SET_SELECTED_GROUP_ARTEFACTS";
export const SET_SELECTED_GROUP_MEMBERS = "SET_SELECTED_GROUP_MEMBERS";
export const SET_USER_DATA_OF_ARTEFACTS = "SET_USER_DATA_OF_ARTEFACTS";
export const ADD_USER_DATA_OF_ARTEFACTS = "ADD_USER_DATA_OF_ARTEFACTS";