export const SET_USER_GROUPS = "SET_USER_GROUPS";
export const SET_SELECTED_GROUP = "SET_SELECTED_GROUP";
export const SET_SELECTED_GROUP_ARTEFACTS = "SET_SELECTED_GROUP_ARTEFACTS";
export const SET_SELECTED_GROUP_MEMBERS = "SET_SELECTED_GROUP_MEMBERS";
export const ADD_SELECTED_GROUP_ARTEFACTS_COMMENTS = "ADD_SELECTED_GROUP_ARTEFACTS_COMMENTS";
export const REQUEST_ALL_SELECTED_GROUP_ARTEFACT_COMMENTS = "REQUEST_ALL_SELECTED_GROUP_ARTEFACT_COMMENTS";
export const RECEIVE_ALL_SELECTED_GROUP_ARTEFACT_COMMENTS = "RECEIVE_ALL_SELECTED_GROUP_ARTEFACT_COMMENTS";