export const C = {
  SET_NAME: "SET_NAME",
  SET_EMAIL: "SET_EMAIL",
  SET_PASSWORD: "SET_PASSWORD",
  SET_PASSWORDCFM: "SET_PASSWORDCFM",
  SET_PHOTO: "SET_PHOTO",
  SET_REGISTER_STAGE: "SET_REGISTER_STAGE",
  RESET_REGISTER_STATE: "RESET_STATE"
};
