export const C = {
  GET_NAME: "GET_NAME",
  GET_EMAIL: "GET_EMAIL",
  GET_PASSWORD: "GET_PASSWORD",
  GET_PASSWORDCFM: "GET_PASSWORDCFM",
  GET_PHOTO: "GET_PHOTO",
  SET_REGISTER_STAGE: "SET_REGISTER_STAGE"
};
